#!/usr/bin/env bash

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Pick an emoji using rofi
##?
##? Requirements:
##?     rofi, xsel, xdotool
##?
##? Usage:
##?    pick
docs::eval "$@"

function display() {
    emoji=$(cat ".cache/emojis.txt" | grep -v '#' | grep -v '^[[:space:]]*$')
    line=$(echo "$emoji" | rofi -theme ~/.dotfiles/linux/i3/slate.rafi -dmenu -i -lines 7 -p emoji -kb-custom-1)
    exit_code=$?

    line=($line)

    if [ $exit_code == 0 ]; then
        echo -n "${line[0]}" | xsel -ipb
        xdotool key Ctrl+Shift+v
    fi
}

if [ ! -f ".cache/emojis.txt" ]; then
    dot emoji download
fi

display