#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/scripts/emoji/.env"

##? Pick an emoji using rofi
##?
##? Requirements:
##?     rofi, xsel, xdotool
##?
##? Usage:
##?    pick
##?
##? Notes:
##?     - A font that supports emoji like "Noto Emoji" or "EmojiOne" is needed.
##?     - Ctrl+C in rofi will copy it to the clipboard.
docs::eval "$@"

function notify() {
    if [ "$(command -v notify-send)" ]; then
        notify-send "$1" "$2"
    fi
}

function display() {
    emoji=$(cat "$EMOJI_FILE" | grep -v '#' | grep -v '^[[:space:]]*$')
    line=$(echo "$emoji" | rofi -theme ~/.dotfiles/linux/i3/slate.rafi -dmenu -i -lines 7 -p emoji -kb-custom-1 Ctrl+c $@)
    exit_code=$?

    line=($line)

    if [ $exit_code == 0 ]; then
        echo -n "${line[0]}" | xsel -ipb
        xdotool key Ctrl+Shift+v
    fi
}

# Download all emoji if they don't exist yet
if [ ! -f "$EMOJI_FILE" ]; then
    dot emoji download
fi

display