#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? List active Docker containers
#?? 1.0.0
##?
##? Usage:
##?   list
docs::eval "$@"


containers=$(docker ps | awk '{if (NR!=1) print $1 ": " $(NF)}')
echo "👇 Containers 👇"
echo $containers