#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? To export your Ubuntu, Python and Node apps
#?? 1.0.0
##?
##? Usage:
##?   export_apps
docs::eval "$@"

# Ubuntu apps
apt list --installed > ~/.dotfiles/linux/apt/apt-installed.txt
echo "Ubuntu apps exported!"

# Python apps
pip freeze > ~/.dotfiles/langs/python/requirements.txt
echo "Python apps exported!"
